app/src/js/action/point_cloud.ts, app/src/js/components/viewer3d.tsx
Currently, the camera movement from key presses and zooms is committed to state each time the UI handler fires, but this causes laggy behavior as the redux state must update very frequently. This PR changes the behavior to only dispatch actions to the store at the end of a scroll or when a user stops pressing a key.
=> Commit camera to state only when user action ends

app/src/js/server/path.ts, app/src/test/server/s3_storage.test.ts
The original s3 test uses a fixed folder for testing, which can cause conflicts when multiple tests are running at the same time.
=> Unique s3 bucket folder name for each test

app/src/js/server/path.ts, app/src/js/server/redis_store.ts, app/src/test/server/redis_store.test.ts
Fixed bug where project name is null. It occurred because we didn't filter out non-reminder keys from the Redis expiration listener. It also explains why it took so long, since normal keys only expire after 1 hour by default. 
Also modified the Redis tests so they fail without this fix.
=> Fix bug where project name is null

app/src/js/components/label2d_canvas.tsx, app/src/js/drawable/2d/label2d_handler.ts, app/src/js/drawable/2d/label2d_list.ts, app/src/test/drawable/label2d_handler.test.ts, app/src/test/project/box2d.disabledtest.tsx
The background state change may interrupt the user drawing action. This PR prevent this from happening by avoiding `updateState` if there are updated labels in `label2DList`. However, How handler, label list and label interact still require scrutinization.
=> updateState doesn't interrupt ongoing drawing

app/src/js/styles/label.tsx
The current version behaves very strangely when you try to edit the number. The cursor is in the wrong position, etc. This happens because it is in right-to-left mode (meant for languages that read right to left). Removing this mode makes it look a bit worse in terms of alignment, but it behaves much better:
=> Fix Numeric Item Selector

app/src/js/action/common.ts, app/src/js/common/session.ts, app/src/js/common/session_setup.tsx, app/src/js/common/simple_store.ts, app/src/js/functional/states.ts, app/src/js/functional/types.ts, app/src/test/components/box2d.test.tsx, app/src/test/components/label2d_canvas.test.tsx, app/src/test/components/label2d_canvas_util.tsx, app/src/test/components/toolbar.test.tsx, app/src/test/components/track.test.tsx, app/src/test/drawable/box2d_label.test.ts, app/src/test/drawable/label2d_handler.test.ts, app/src/test/drawable/label2d_handler_util.ts, app/src/test/drawable/track_label.test.ts, app/src/test/server/util/track_collector.ts, app/src/test/util/label_collector.ts, app/src/test/util/shape.ts
- Same `CheckBox2D` between components and drawable
- Replace element-wise checking with object-level checking
- Remove the global variable 
- `2DBox` -> `Box2D` for consistency
- Polygon checking is not changed significantly due to forthcoming shape refactoring
=> Make the box2d testing procedure consistent and simplified

app/src/js/common/window.ts, app/src/js/components/label2d_canvas.tsx, app/src/js/components/util.ts, app/src/js/drawable/2d/label2d_handler.ts, package-lock.json, package.json
CMD key can bring the interface into special labeling mode. But CMD+TAB can switch to another window and keep the current scalable canvas on the special mode. As shown in the gif below, when the user goes back to the scalabel window by mouse click, the label drawing can fail to finish unless CMD key is pressed again. This PR fixes this issue by adding a window visibility listener and using it in the handler.
=> Fix meta/control key capture issue during window switch

app/src/js/functional/states.ts, app/src/test/functional/state.test.ts
The bug is that attributes would change for unselected labels. 
The cause is that the selected labels are used to initialize labels, but are not copied. Thus changes in the selection propagate to previous labels.
The fix is to make a deep clone of the selected labels before using them to initialize a new label.
=> Fix changing attributes

app/src/js/drawable/2d/box2d.ts, app/src/js/drawable/2d/label2d.ts, app/src/js/drawable/2d/polygon2d.ts
This PR is based on #163. This one uses high-level vector API and supports both polygon and polyline.
=> Show tags for polygon and polyline

app/src/js/common/track/policy/linear_interpolation/box2d_linear_interpolation.ts, app/src/js/functional/states.ts, app/src/test/components/track.test.tsx
=> Enable bounding box linear interpolation

app/src/js/server/logger.ts, app/src/js/server/redis_store.ts, app/src/js/server/storage.ts, app/src/test/server/file_storage.test.ts, app/src/test/server/redis_store.test.ts
When the redis is running for a long time, it may run out of memory and evict keys randomly. So if a key is not available in redis, it doesn't mean it doesn't exit on the storage. This PR fixes the problem. When the key is missing on radis, `RedisStore` will search the storage. If it is successful, the value will be retrieved and stored in the redis store.
=> Handle missing redis keys

app/src/js/server/logger.ts
This is consistent with the convention of redis. Also added hostname and pid to tell the node process identity.
=> Use local time in logger

app/src/js/server/logger.ts, app/src/js/server/redis_store.ts
The current dependency may lead to error in the case of LRU eviction. Also, It is better to have as little key dependency as possible to improve the system robustness.
=> Remove metakey dependency in Redis writeback

app/src/js/server/s3_storage.ts, app/src/test/server/s3_storage.test.ts
Each S3 storage testing is in a new S3 bucket to avoid bucket name conflicts between different runs. This can support running s3 storage test under different AWS accounts.
=> Create a new bucket for each s3 unit test run

scalabel/label/to_coco.py
-h always means "--help", we should not overload this argument
=> remove height abbreviation -h

app/src/components/toolbar.tsx, app/src/components/toolbar_list_button.tsx
=> Fix highlighting of toolbar buttons for image tags

scalabel/label/io.py
The load function will raise a Value error with message "Inputs must be a folder or a JSON file." when it actually should raise a FileNotFoundError.
=> Fix misleading error msg when 'inputs' not exists in load

scalabel/eval/mot.py
One new param was added to the function `acc_single_video_mot` in [PR 328](https://github.com/scalabel/scalabel/pull/328).
This function will be used as a parameter (with typing `VideoFunc`) for the function `evaluation_track`.
However, the definition `VideoFunc` lacks a corresponding re-definition.
This static error was not detected by mypy.
=> add bool to the VideoFunc definition

app/src/server/bdd_type_transformers.ts, app/src/server/create_project.ts, app/src/server/export.ts, app/src/server/import.ts, app/src/types/export.ts, app/src/types/project.ts, app/test/server/create_project.test.ts, app/test/server/export.test.ts, app/test/test_states/sample_state_3d_box.json, app/test/test_states/test_creation_objects.ts, app/test/test_states/test_export_objects.ts
- Update export format of 3d bounding boxes and camera parameters to match python library (and documentation).
- Import labels based on project label types. This fixes the bug where box2d labels override box3d labels during import even in a project set up for 3d bounding box labeling.
- This will break backwards compatibility. Existing exports in the old format will no longer import correctly.
=> 3d import export

doc/src/format.rst, examples/kitti/kitti_categories.yml, examples/kitti/kitti_list.json, examples/kitti/kitti_sensors.json
Visualisation example of pointclouds (converted from the default `.bin` to Scalabel-compatible `.ply`) and four corresponding images (two RGB, two grayscale) using KITTI velodyne dataset.
=> KITTI velodyne dataset example

app/src/components/point_cloud_canvas.tsx
- Fixes bug where point cloud canvas would not update the point cloud state when changing item
- Open any point cloud project, and navigate between items. The point cloud should update per item.
=> Fix point cloud canvas not updating point cloud

scalabel/eval/boundary.py, scalabel/eval/pan_seg.py, scalabel/eval/result.py, scalabel/eval/sem_seg.py, scalabel/eval/tagging.py
Pydantic expects `include: Union['AbstractSetIntStr', 'MappingIntStrAny'] = None` to be passed into `dict()`, but we are passing in `include: Optional[AbstractSet[str]]`. Technically, we have the correct type, because the value is allowed to be `None`. Since this issue is part of Pydantic, we will ignore them for now.
=> Ignore type for include and exclude
