scalabel/scalabel

- app/src/js/common/track.ts
- app/src/js/common/track_policies/custom_label_linear_interpolation_policy.ts
- app/src/js/common/track_policies/track_policy.ts
- app/src/js/common/types.ts
- app/src/js/components/create_form.tsx
- app/src/js/drawable/2d/custom_label.ts
- app/src/js/drawable/2d/label2d.ts
- app/src/js/drawable/2d/node2d.ts
- app/src/js/functional/types.ts
- app/src/js/server/hub.ts
- app/src/js/server/util.ts
- app/src/js/styles/create.tsx
- app/src/test/drawable/label2d_handler.test.ts
Add tracking & vertex deletion. Still need to display tags for vertices
> Finish up custom label 2d MVP

- app/src/js/components/drawable_viewer.tsx
- app/src/js/components/viewer2d.tsx
- app/src/js/components/viewer3d.tsx
- app/src/js/styles/label.tsx
- app/src/js/styles/viewer.tsx
> Add zoom buttons for 2d labeling & fix border issue

- app/src/js/common/session.ts
- app/src/js/common/synchronizer.ts
- app/src/js/components/title_bar.tsx
- app/src/js/server/hub.ts
- Made 'saved' text disappear if user takes a new action, e.g. making a new box
- Fixed manual saving issue where boxes not saved disappear after disconnect
- Fixed autosave issue where user could 'unfreeze' screen after disconnect
> Fix bugs in manual and auto saving

- README.md
- package-lock.json
- package.json
> Update webpack instructions

- app/src/js/components/tag_3d_canvas.tsx
- app/src/js/components/viewer3d.tsx
- app/src/js/drawable/3d/label3d_list.ts
Show 3D label categories at position of projection of 3D label center onto screen.
Before:
After:
> Render categories of 3D labels

- Dockerfile
- README.md
> Fix docker node js version

- app/src/js/components/label_pane.tsx
- app/src/js/components/point_cloud_canvas.tsx
- app/src/js/components/viewer3d.tsx
- app/src/js/functional/common.ts
- app/src/js/functional/states.ts
- app/src/js/functional/types.ts
> Enable hiding panes

- app/src/js/components/window.tsx
> disable default scroll and pinch-to-zoom behaviors

- app/src/js/server/create_project.ts
- app/src/js/server/defaults.ts
- app/src/js/server/hub.ts
- app/src/js/server/main.ts
- app/src/js/server/redis_store.ts
- app/src/js/server/types.ts
- app/src/js/server/util.ts
- app/src/test/server/redis_store.test.ts
This can make the use case like #64 easier when docker is used.
> Add item dir in config and restructure the config code

- app/src/js/server/hub.ts
- app/src/js/server/main.ts
- app/src/js/server/project_store.ts
- app/src/js/server/storage.ts
- app/src/js/server/types.ts
- app/src/js/server/user_manager.ts
- app/src/js/server/util.ts
- app/src/test/project/box2d.test.tsx
- app/src/test/server/hub.test.ts
- app/src/test/server/user_manager.test.ts
Fixed user count issue by clearing the user data whenever the server crashes. Also refactored the user management code for clarity.
> Fix User Count

- app/src/js/components/label_pane.tsx
- app/src/js/components/point_cloud_canvas.tsx
- app/src/js/drawable/3d/control/rotation_control.ts
- app/src/js/drawable/3d/cube3d.ts
Make pane buttons vertical
Make points inside box red
> Small tweaks

- app/src/js/common/session.ts
- app/src/js/common/session_init.tsx
- app/src/js/common/session_status.ts
- app/src/js/common/synchronizer.ts
- app/src/js/components/drawable_canvas.ts
- app/src/js/components/title_bar.tsx
- app/src/js/components/viewer.ts
- app/src/js/functional/states.ts
- app/src/js/functional/types.ts
- app/src/js/server/bot.ts
- app/src/js/server/create_project.ts
- app/src/js/server/hub.ts
- app/src/js/server/types.ts
- app/src/test/common/synchronizer.test.tsx
- app/src/test/components/titlebar.test.tsx
- app/src/test/project/box2d.test.tsx
- app/src/test/project/util.tsx
- app/src/test/sample_project.json
- app/src/test/server/bot.test.ts
- app/src/test/test_creation_objects.ts
- Added model compute progress as part of session status
- Refactored session status code
> Model compute status banner

- app/src/js/components/toolbar.tsx
Toolbar button will show up even not in track mode.
Check it via state.task.config.tracking
> Fix button visibility

- app/src/js/components/label2d_canvas.tsx
- app/src/js/components/toolbar.tsx
- app/src/test/components/label2d_canvas.test.tsx
- app/src/test/components/label2d_canvas_util.ts
- app/src/test/drawable/label2d_handler.test.ts
- app/src/test/drawable/label2d_handler_util.ts
- package.json
This new function removes the redundant polygon creation code.
> Add drawPolygon for label2d handler

- app/src/js/server/bot.ts
- app/src/test/server/bot.test.ts
- app/src/test/util.ts
This was an issue with the bot store. The bot state was invalid since it didn't dispatch the predicted actions before broadcasting them. This PR fixes the bug and adds tests for the bot state.
> Fix bug with changing polygon shape

- .vscode/launch.json
- app/src/js/action/select.ts
- app/src/js/common/cognito.ts
- app/src/js/common/session_init.tsx
- app/src/js/common/track/policy/linear_interpolation/polygon_linear_interpolation.ts
- app/src/js/common/track/track.ts
- app/src/js/components/label_layout.tsx
- app/src/js/components/toolbar.tsx
- app/src/js/drawable/2d/label2d.ts
- app/src/js/drawable/2d/label2d_handler.ts
- app/src/js/drawable/2d/polygon2d.ts
- app/src/js/functional/common.ts
- app/src/test/actions/link.test.ts
- app/src/test/actions/track.test.ts
- app/src/test/components/toolbar.test.tsx
Track color will get changed between start drawing and finally drawn.
It is because at first the 'label' has no track id. So the color uses its label id. But when drawn, the labels and new track is committed, those labels will have a track id. The color policy uses the track id. So the color changed.
> Fix track color change problems and parent problems.

- app/src/js/action/track.ts
- app/src/js/drawable/2d/box2d.ts
- app/src/js/drawable/2d/label2d.ts
- app/src/js/drawable/3d/box3d.ts
- app/src/js/drawable/3d/label3d.ts
- app/src/js/drawable/3d/label3d_handler.ts
- app/src/js/drawable/3d/object3d.ts
- app/src/js/drawable/3d/plane3d.ts
- app/src/js/drawable/3d/shape3d.ts
- app/src/js/functional/common.ts
- app/src/js/functional/states.ts
- app/src/js/server/export.ts
- app/src/test/test_states/sample_state.json
- app/src/test/test_states/sample_state_polygon.json
> Fix tracking export id connection

- app/src/js/components/create_project.tsx
- app/src/js/server/file_storage.ts
- app/src/js/server/main.ts
- app/src/js/server/path.ts
- app/src/js/server/project_store.ts
- app/src/js/server/s3_storage.ts
- app/src/js/server/storage.ts
- app/src/js/server/util.ts
- app/src/test/server/file_storage.test.ts
- app/src/test/server/s3_storage.test.ts
- app/src/test/server/util.test.ts
- app/src/test/server/util/util.ts
After this PR, we will be able to store additional store independent information, such as user info, in other folders.
> Move project folders to projects/

- app/src/js/styles/label.tsx
> Add slider right margin for easier clicking

- app/src/js/common/synchronizer.ts
- app/src/js/server/redis_store.ts
> Fix sync message loop

- app/src/js/components/toolbar.tsx
- app/src/js/components/toolbar_category.tsx
- app/src/js/styles/label.tsx
- app/src/test/components/toolbar.test.tsx
- app/src/test/setup/setup_jest_after_env.ts
- package-lock.json
- package.json
This PR uses button group instead of radio controls for category selection. This makes the category labels easier to select.
Before
After
> Change category selection from radio to buttons

- app/src/js/server/hub.ts
- app/src/js/server/logger.ts
- app/src/js/server/util.ts
The current log is too verbose for production and the amount of message data may overflow the log file storage space.
> Add log level setting and config it in command line

- app/config/bot_config.yml
- app/config/default_config.yml
- app/config/s3_config.yml
- app/config/test_config.yml
- app/src/js/const/config.ts
- app/src/js/server/config.ts
- app/src/js/server/controller/callback.ts
- app/src/js/server/defaults.ts
- app/src/js/server/hub.ts
- app/src/js/server/main.ts
- app/src/js/server/middleware/errorHandler.ts
- app/src/js/server/redis_store.ts
- app/src/js/server/util.ts
- app/src/js/types/config.ts
- app/src/test/project/box2d.disabledtest.tsx
- app/src/test/server/redis_store.test.ts
Backward compatibility of storage fields is kept.
> Reorganize server config fields for clarity and extensibility

- app/config/s3_config.yml
- app/src/common/session_init.tsx
- app/src/server/listeners.ts
- app/src/server/s3_storage.ts
- app/test/server/s3_storage.test.ts
Fixes some issues with the logging for project creation with s3 storage
> Fix error logging

- app/src/components/button.tsx
- app/src/components/label_layout.tsx
- app/src/components/toolbar.tsx
- app/src/components/toolbar_category.tsx
- app/src/components/toolbar_list_button.tsx
- app/src/styles/label.ts
- app/test/components/toolbar.test.tsx
- app/test/components/track.test.tsx
- The elements are perfectly centered
- Smaller but still eligible elements
- Fix alignment issues
Before
After
> Dense Toolbar Design

- scalabel/label/io.py
- scalabel/label/io_test.py
> consider the scenario that a json file contains a dict instead of a list of dict

- scalabel/label/from_coco.py
- scalabel/label/io.py
- scalabel/label/io_test.py
- scalabel/label/to_coco.py
- scalabel/vis/labels.py
Apply `load` with `nprocs` to all references.
Use 'pmap' for `dump` and `save`.
> Apply pmap to more functions

- scalabel/label/coco_typing.py
according to https://cocodataset.org/#format-data
> add coco panoptic segmentation format

- scalabel/label/from_waymo.py
- scalabel/label/testcases/waymo_cam_anns.json
- scalabel/label/testcases/waymo_lidar_anns.json
Waymo attributes "time_of_day", "location" and "weather" are now converted to Scalabel. Testcases were modified accordingly.
> Added functionality to convert Waymo attributes to Scalabel format

- doc/src/label.rst
- doc/src/visual.rst
- scalabel/eval/detect.py
- scalabel/eval/mot.py
- scalabel/label/from_kitti.py
- scalabel/label/from_waymo.py
- scalabel/tools/detect_ground.py
- scalabel/vis/controller.py
- scalabel/vis/label.py
Add a range_begin and range_end attribute to the controller config and as cmd line options, s.t. one can specify which frames to visualize in scalabel.vis.label
> add range option to controller config

- .github/workflows/deploy-doc.yml
- .pylintrc
- scalabel/__init__.py
- scalabel/common/__init__.py
- scalabel/common/logger.py
- scalabel/common/quiet.py
- scalabel/common/tqdm.py
- scalabel/eval/detect.py
- scalabel/eval/detect_test.py
- scalabel/eval/mot.py
- scalabel/eval/mot_test.py
- scalabel/eval/result.py
- scalabel/label/from_coco.py
- scalabel/label/from_kitti.py
- scalabel/label/from_waymo.py
- scalabel/label/to_coco.py
- scalabel/tools/edit_labels.py
- scalabel/tools/launch_server.py
- scalabel/tools/prepare_data.py
- scalabel/vis/geometry.py
- scalabel/vis/label.py
add a global quiet option for all logging / tqdm s.t. eval can be called without logging. Fix deploy-doc workflow file
> add quiet option for logging, fix deploy-doc workflow

- scalabel/vis/controller.py
- scalabel/vis/helper.py
- scalabel/vis/label.py
> Adding visualization code for Graph type

- app/src/common/split_pane/README.md
This file was missing from the previous PR.
> Add notice for split_pane

- README.md
> Always upgrade during pip install

- app/src/common/sensor.ts
- app/src/drawable/3d/box3d.ts
- app/src/drawable/3d/cube3d.ts
- app/src/drawable/3d/label3d_handler.ts
- app/src/types/export.ts
- app/src/types/state.ts
- Visualization of "forward direction" for 3D bounding boxes (see image below).
- Add "height" field for sensors, to help with 3D annotation in cases where a 3D reconstruction is not available, and the height of the sensor above the ground is known.
> 3d box heading

- scalabel/eval/boundary.py
- scalabel/eval/pan_seg.py
- scalabel/eval/result.py
- scalabel/eval/sem_seg.py
- scalabel/eval/tagging.py
- scalabel/label/io.py
> Fix config check in label

- app/src/server/create_project.ts
- scalabel/common/parallel.py
- scalabel/eval/tagging.py
Fix a bug that it cannot parse dataset JSON file with `subcategories` fields having `null`.
> Fix subcategories parsing
